### ISSUE TITLE
[0 Zome Functions] Test fails with installedApp.slots being undefined

### ISSUE THREAD

**Issue by jost-s** [holochain-gym/developer-exercises#40]
Following the first exercise and running the test via `npm test`, I run into an error:
```
07:27:14 [tryorama] info: Conductor 'c0' process spawning completed.
App Port spun up on port  50261
07:27:14 [tryorama] error: Test error: 'TypeError: Cannot convert undefined or null to object\n' +
  '    at Function.entries (<anonymous>)\n' +
  '    at Conductor._makeInstalledAgentHapp (/Users/jost/Desktop/dev/holochain/developer-exercises/1.basic/0.zome-functions/exercise/tests/node_modules/@holochain/tryorama/src/conductor.ts:237:26)\n' +
  '    at Conductor.<anonymous> (/Users/jost/Desktop/dev/holochain/developer-exercises/1.basic/0.zome-functions/exercise/tests/node_modules/@holochain/tryorama/src/conductor.ts:230:17)\n' +
  '    at Generator.next (<anonymous>)\n' +
  '    at fulfilled (/Users/jost/Desktop/dev/holochain/developer-exercises/1.basic/0.zome-functions/exercise/tests/node_modules/@holochain/tryorama/lib/conductor.js:24:58)\n' +
  '    at processTicksAndRejections (internal/process/task_queues.js:97:5)'
not ok 1 Test threw an exception. See output for details.
  ---
    operator: fail
    at: <anonymous> (/Users/jost/Desktop/dev/holochain/developer-exercises/1.basic/0.zome-functions/exercise/tests/node_modules/@holochain/tryorama/src/middleware.ts:137:13)
    stack: |-
      Error: Test threw an exception. See output for details.
          at Test.assert [as _assert] (/Users/jost/Desktop/dev/holochain/developer-exercises/1.basic/0.zome-functions/exercise/tests/node_modules/tape/lib/test.js:304:54)
          at Test.bound [as _assert] (/Users/jost/Desktop/dev/holochain/developer-exercises/1.basic/0.zome-functions/exercise/tests/node_modules/tape/lib/test.js:91:32)
          at Test.fail (/Users/jost/Desktop/dev/holochain/developer-exercises/1.basic/0.zome-functions/exercise/tests/node_modules/tape/lib/test.js:398:10)
          at Test.bound [as fail] (/Users/jost/Desktop/dev/holochain/developer-exercises/1.basic/0.zome-functions/exercise/tests/node_modules/tape/lib/test.js:91:32)
          at /Users/jost/Desktop/dev/holochain/developer-exercises/1.basic/0.zome-functions/exercise/tests/node_modules/@holochain/tryorama/src/middleware.ts:137:13
          at processTicksAndRejections (internal/process/task_queues.js:97:5)
  ...
07:27:14 [tryorama] info: conductor 'c0' exited with code null
FIXME: ignoring onLeave
```

All steps run fine when run individually, except the Tryorama one. When debugging `Conductor._makeInstalledAgentHapp`, it turns out that `installedApp.slots` is `undefined`. Could that be to do with me using the nightly holochain build?

**Comment by guillemcordoba** [comment]
Yes that's totally it. Your version of holochain is compatible with tryorama v0.4.3, as opposed to the 0.4.1 that is compatible with the gym's default.nix. I'm waiting on [this](https://github.com/holochain/holochain/issues/872) to lock in holochain and tryorama release versions.

**Comment by guillemcordoba** [comment]
Thanks for all the feedback as well! Would you want to join us in the holochain in action weekly meetings? https://www.youtube.com/channel/UCJwIuwkCI5HMSzHJpKys-RQ

**Comment by jost-s** [comment]
Definitely! Nice synchronicity, I was looking up this morning when these meetings are and how to join them 😀

**Comment by guillemcordoba** [comment]
@jost-s Can you pull again and retry going into the nix-shell and running the tests?

**Comment by jost-s** [comment]
I pulled and compiled successfully 🎉 

Running `npm test` results in a timeout
```
☸☸☸ {{{CONDUCTOR c0}}}
☸ note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
☸ 
21:20:11 [tryorama] error: Test error: 'Error: Timed out in 15000ms: activate_app\n' +
  '    at Timeout.<anonymous> (/Users/jost/Desktop/dev/holochain/developer-exercises/1.basic/0.zome-functions/exercise/tests/node_modules/@holochain/conductor-api/src/websocket/common.ts:16:14)\n' +
  '    at listOnTimeout (internal/timers.js:554:17)\n' +
  '    at processTimers (internal/timers.js:497:7)'
not ok 1 Test threw an exception. See output for details.
  ---
    operator: fail
    at: <anonymous> (/Users/jost/Desktop/dev/holochain/developer-exercises/1.basic/0.zome-functions/exercise/tests/node_modules/@holochain/tryorama/src/middleware.ts:138:13)
    stack: |-
      Error: Test threw an exception. See output for details.
          at Test.assert [as _assert] (/Users/jost/Desktop/dev/holochain/developer-exercises/1.basic/0.zome-functions/exercise/tests/node_modules/tape/lib/test.js:304:54)
          at Test.bound [as _assert] (/Users/jost/Desktop/dev/holochain/developer-exercises/1.basic/0.zome-functions/exercise/tests/node_modules/tape/lib/test.js:91:32)
          at Test.fail (/Users/jost/Desktop/dev/holochain/developer-exercises/1.basic/0.zome-functions/exercise/tests/node_modules/tape/lib/test.js:398:10)
          at Test.bound [as fail] (/Users/jost/Desktop/dev/holochain/developer-exercises/1.basic/0.zome-functions/exercise/tests/node_modules/tape/lib/test.js:91:32)
          at /Users/jost/Desktop/dev/holochain/developer-exercises/1.basic/0.zome-functions/exercise/tests/node_modules/@holochain/tryorama/src/middleware.ts:138:13
  ...
21:22:01 [tryorama] error: 
The following conductors were forcefully shutdown after 125 seconds of no activity:

```

**Comment by jost-s** [comment]
> Thanks for all the feedback as well! Would you want to join us in the holochain in action weekly meetings? https://www.youtube.com/channel/UCJwIuwkCI5HMSzHJpKys-RQ

@guillemcordoba I don't know how else to reach you actually 😁 I used to have appointments at 5 pm on Tuesday but am happy to shift them to free myself for the HIA meetings. So today I'd join a bit later and next week as well. How do I participate?

**Comment by guillemcordoba** [comment]
Okey that's perfect. To join, there is this form that you can fill: https://dawumck27xt.typeform.com/to/uZTCoYs1.

If you have any problems ping me in the holochain forum this afternoon and I'll let you in :D

**Comment by jost-s** [comment]
Actually what I omitted previously is this part before the timeout
```
22:02:23 info: 
☯☯☯ {{{CONDUCTOR c0}}}
☯ FATAL PANIC PanicInfo {
☯     payload: 
22:02:23 info: 
☸☸☸ {{{CONDUCTOR c0}}}
☸ Any { .. },
☸     message: Some(
☸         called `Option::unwrap()` on a `None` value,
☸     ),
☸     location: Location {
☸         file: "crates/kitsune_p2p/kitsune_p2p/src/gossip/simple_bloom.rs",
☸         line: 169,
☸         col: 14,
☸     },
☸ }
☸ thread 'holochain-tokio-thread' panicked at 'called `Option::unwrap()` on a `None` value', crates/kitsune_p2p/kitsune_p2p/src/gossip/simple_bloom.rs:169:14
```

I don't know if that is helpful.

**Comment by jost-s** [comment]
The test for the second exercise fails for the same reason btw.

**Comment by jost-s** [comment]
Coincidentally I just read the chapter on Enums in my Rust study, and the API doc says
```rust
pub const fn unwrap(self) -> T
```

> Returns the contained Some value, consuming the self value.

> Because this function may panic, its use is generally discouraged. Instead, prefer to use pattern matching and handle the None case explicitly, or call unwrap_or, unwrap_or_else, or unwrap_or_default.

Well, confirmed from real life experience 😀

**Comment by guillemcordoba** [comment]
No worries :)

Actually that right there should be a bug in holochain core... I'm a bit indecisive about what to do in the gym right now, because in the core team they are trying to fix the tryorama `21:20:11 [tryorama] error: Test error: 'Error: Timed out in 15000ms: activate_app\n' `. I'll send your bug along also.

**Comment by jost-s** [comment]
Alright, gotcha, it's the error you mentioned above and it's in progress.

Cool, I'm playing around directly with Tryorama in the meanwhile, lots to learn there 👍

**Comment by jost-s** [comment]
I cannot reproduce this error anymore and consider it solved. Thanks for your help, @guillemcordoba
